# Generated by Django 3.1.4 on 2020-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_code',
            field=models.CharField(max_length=255),
        ),
    ]
