# Generated by Django 3.1.4 on 2020-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201225_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currenet_location',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_project',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_code',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
