# Generated by Django 3.1.5 on 2021-01-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201227_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currenet_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
