# Defining version of docker-compose
version: "3"

# Next we define the services that make up our application
services:
  web_app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./web_app:/web_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=web_app
  #     - DB_USER=postgres
  #     - DB_PASS=supersecretpassword
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:10-alpine
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=supersecretpassword